version: '2.0'
services:
  # https://hub.docker.com/_/mysql/
  mysql:
    image: mysql:5.7
    volumes:
      - datastore:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: laravel
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password

  app:
    build: php/.
    volumes:
      - ${LARAVEL_PATH}:/var/www/html
    links:
      - mysql
    ports:
      - 80:80

volumes:
  datastore: {}
  cache: {}
